# Generated by Django 5.1.15 on 2025-12-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="interest",
            field=models.CharField(
                choices=[("seller", "Vender gado"), ("buyer", "Comprar gado (Frigorífico)")],
                default="seller",
                max_length=20,
            ),
        ),
    ]
