# Generated by Django 5.1.15 on 2025-12-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_lead_interest"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="animal_category",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="lead",
            name="avg_weight_kg",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="breed",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="lead",
            name="city_state",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="lead",
            name="desired_volume",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="lead",
            name="heads",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="specs",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="timeframe",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="lead",
            name="interest",
            field=models.CharField(
                choices=[
                    ("seller", "Vender gado"),
                    ("buyer", "Comprar gado (Frigorífico)"),
                    ("other", "Outros assuntos"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
