# Generated by Django 5.1.15 on 2025-12-23 20:00

from django.db import migrations, models


def create_default_message_templates(apps, schema_editor):
    MessageTemplate = apps.get_model("leads", "MessageTemplate")

    templates = [
        {
            "channel": "email",
            "title": "Comesul Beef – alinhamento de padrão de compra (e-mail)",
            "subject": "GetAgro – alinhamento de padrão de compra (gado de corte RS)",
            "body": "Olá, Lúcio, tudo bem?\n\nAqui é o Douglas (da lavanderia que atende a Comesul Beef na lavagem de uniformes).\n\nEstou estruturando um projeto no RS chamado GetAgro, com o objetivo de intermediar compra e venda de gado de corte com curadoria (vídeo + dados completos) e acompanhamento até o fechamento. A ideia é encaminhar apenas oportunidades alinhadas ao perfil de compra de vocês, de forma padronizada e objetiva.\n\nPara eu dimensionar e já começar a enviar lotes no padrão correto, você poderia me informar, por gentileza:\n\n1) Categoria principal de compra (boi gordo, vaca descarte, novilho etc.)\n2) Peso mínimo/médio e padrão de acabamento/idade (se aplicável)\n3) Preferência de raça/padrão (se houver)\n4) Região/raio de compra (ex.: até X km de Pantano Grande/RS)\n5) Forma e prazo de pagamento\n6) Melhor formato para envio das ofertas (WhatsApp com ficha + vídeo, e/ou e-mail)\n\nCom isso eu consigo filtrar e te mandar somente o que realmente serve, sem tomar teu tempo.\n\nAtenciosamente,\nDouglas Herzog\nGetAgro\nRio Pardo/RS\n",
        },
        {
            "channel": "whatsapp",
            "title": "Comesul Beef – follow-up após e-mail (WhatsApp)",
            "subject": "",
            "body": "Oi, Lúcio, tudo bem? Aqui é o Douglas (lavanderia).\n\nTe enviei agora um e-mail no compras@comesulbeef.com.br sobre a GetAgro, pra alinhar o padrão de compra de vocês e eu te mandar somente lotes de gado de corte dentro do perfil (com ficha + vídeo).\n\nQuando puder, dá uma olhada. Se preferir, eu resumo por aqui também.",
        },
        {
            "channel": "whatsapp",
            "title": "Captação de vendedor – coleta de dados do lote (WhatsApp)",
            "subject": "",
            "body": "Oi, [NOME], aqui é o Douglas. Tudo bem?\n\nEstou trabalhando com a GetAgro aqui no RS, fazendo a ponte entre quem vende gado de corte e compradores (incluindo frigorífico), com acompanhamento até fechar.\nComissão só em negócio fechado: 1,5% do vendedor + 1,5% do comprador.\n\nSe você tiver lote pra vender, me manda por favor:\n1) Cidade/RS\n2) Categoria (boi gordo / novilho / vaca descarte / etc.)\n3) Quantidade de cabeças\n4) Peso médio (ou faixa)\n5) Vídeo curto (30–60s) + 2–3 fotos\n6) Preço pedido (se tiver) ou “aceito proposta”\n\nCom isso eu já consigo encaminhar e te dar retorno rápido.",
        },
        {
            "channel": "whatsapp",
            "title": "Oferta de lote – ficha padrão (WhatsApp)",
            "subject": "",
            "body": "LOTE RS – [CATEGORIA]\n📍 Local: [Cidade/RS] (aprox. [X] km de Pantano Grande / Comesul)\n🐂 Qtde: [N] cabeças\n⚖️ Peso médio: [___ kg] (faixa: [min–max] se houver)\n🧬 Padrão/raça: [ex.: britânico / cruzado / zebuíno]\n📌 Condição: [a pasto / semiconfinado / confinamento]\n📅 Disponível: [imediato / data]\n💰 Preço: [R$ ___] ou “aberto a proposta”\n🚚 Frete: [por conta de ___]\n📹 Vídeo/fotos: [anexo/link]\n\nSe tiver interesse, me responde “TENHO INTERESSE” que eu já confirmo condições e avanço com o vendedor.",
        },
        {
            "channel": "whatsapp",
            "title": "Follow-up comprador (WhatsApp)",
            "subject": "",
            "body": "Oi, [NOME]. Conseguiu ver o lote de [cidade]?\n\nSe não estiver no padrão, me diz só:\n- categoria preferida\n- peso mínimo\n- faixa de preço\nque eu ajusto e te mando algo mais alinhado.",
        },
        {
            "channel": "whatsapp",
            "title": "Fechamento + comissão (WhatsApp)",
            "subject": "",
            "body": "Fechamos assim:\n\n✅ Lote: [categoria] – [N] cabeças – [cidade/RS]\n✅ Preço: R$ [___] ([por cabeça / por kg / total])\n✅ Retirada/Entrega: [local/data]\n✅ Pagamento: [forma/prazo]\n✅ Frete: [quem paga]\n\nComissão de intermediação (somente em negócio fechado):\n- 1,5% comprador\n- 1,5% vendedor\n\nSe estiver ok, eu confirmo com a outra parte e formalizo aqui por mensagem.",
        },
    ]

    for t in templates:
        MessageTemplate.objects.get_or_create(
            channel=t["channel"],
            title=t["title"],
            defaults={
                "subject": t["subject"],
                "body": t["body"],
                "is_active": True,
            },
        )


def remove_default_message_templates(apps, schema_editor):
    MessageTemplate = apps.get_model("leads", "MessageTemplate")
    MessageTemplate.objects.filter(
        title__in=[
            "Comesul Beef – alinhamento de padrão de compra (e-mail)",
            "Comesul Beef – follow-up após e-mail (WhatsApp)",
            "Captação de vendedor – coleta de dados do lote (WhatsApp)",
            "Oferta de lote – ficha padrão (WhatsApp)",
            "Follow-up comprador (WhatsApp)",
            "Fechamento + comissão (WhatsApp)",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_lead_profile_fields_and_interest_other"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("channel", models.CharField(choices=[("whatsapp", "WhatsApp"), ("email", "E-mail")], max_length=20)),
                ("title", models.CharField(max_length=160)),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["channel", "title"],
            },
        ),
        migrations.RunPython(create_default_message_templates, remove_default_message_templates),
    ]
