# Generated by Django 5.1.15 on 2025-12-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_add_cep"),
        ("listings", "0001_initial"),
        ("leads", "0004_message_template"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Procura",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("specs", models.TextField(blank=True)),
                ("desired_volume", models.CharField(blank=True, max_length=120)),
                ("city_state", models.CharField(blank=True, max_length=120)),
                ("heads", models.PositiveIntegerField(blank=True, null=True)),
                ("avg_weight_kg", models.PositiveIntegerField(blank=True, null=True)),
                ("animal_category", models.CharField(blank=True, max_length=80)),
                ("breed", models.CharField(blank=True, max_length=80)),
                ("timeframe", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procuras",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="source",
            field=models.CharField(
                choices=[
                    ("legacy_form", "Formulário"),
                    ("listing", "Interesse em anúncio"),
                    ("procura", "Interesse em procura"),
                ],
                default="legacy_form",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Novo"),
                    ("in_progress", "Em andamento"),
                    ("contact_released", "Contato liberado"),
                    ("closed", "Fechado"),
                    ("lost", "Perdido"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="contact_release",
            field=models.CharField(
                choices=[
                    ("none", "Não liberar"),
                    ("both", "A) Liberar para ambos"),
                    ("seller_only", "B) Liberar só do vendedor"),
                    ("buyer_only", "C) Liberar só do comprador"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="contact_released_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="listings.listing",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="procura",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="leads.procura",
            ),
        ),
    ]
