# Generated by Django 5.1.15 on 2025-12-24 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_profile_cpf_per_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('lot', 'Lote'), ('animal', 'Animal')], max_length=10)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('heads', models.PositiveIntegerField(blank=True, null=True)),
                ('avg_weight_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('animal_category', models.CharField(blank=True, max_length=80)),
                ('breed', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
